### ISSUE TITLE
When I use vs2017 to compile this project, It's occurs  a C2975 error.

### ISSUE THREAD

**Issue by BboyHanat** [sxyu/smplxpp#1]
In smplx.hpp, line 120.
 It's same like vs2017 is not allowd templete to get a value from a function or variable expression.

**Comment by sxyu** [comment]
Hi, did you resolve this issue? vs2017 is supposed to support C++14, so that's pretty strange. I was able to get the project to build with vs2019. 
You can probably replace it with Eigen::Dynamic if it is a problem.

**Comment by BboyHanat** [comment]
> Hi, did you resolve this issue? vs2017 is supposed to support C++14, so that's pretty strange. I was able to get the project to build with vs2019.
> You can probably replace it with Eigen::Dynamic if it is a problem.

It’s solved by this code:
`Eigen::Matrix<Scalar, Eigen::Dynamic, Model::n_blend_shapes()> blend_shapes;`
It same like compiler can not find "n_blend_shapes()" function, so I add “Model::” in front of n_blend_shapes.

**Comment by sxyu** [comment]
OK, I've changed it. Might be compiler bug?

**Comment by BboyHanat** [comment]
> OK, I've changed it. Might be compiler bug? Or maybe it is actually UB.

I think it's a  compiler bug.
