### ISSUE TITLE
About zlib include directory.

### ISSUE THREAD

**Issue by BboyHanat** [sxyu/smplxpp#2]
I find "include_directories(${ZLIB_DIR}/include)" in your CMakeList.txt, but I can't find that "include" directory in "ZLIB_DIR".
Is there need to make this  "include" directory by manually?

**Comment by sxyu** [comment]
Hi,
Good catch. By default, the CMakeLists uses the system zlib, so I didn't notice the error. Hopefully I've fixed it now.
-Alex
