### ISSUE TITLE
Assertion error when viewing SMPL-X model

### ISSUE THREAD

**Issue by nandbhat** [sxyu/smplxpp#3]
```
smplx assertion FAILED: m.shape[idx] == dim (400 != 20)
  at /home/nandan/Work/vvc/smplx_research/smplxpp/src/util.cpp line 150

```
when running "smplx-viewer X"
Using SMPL-X v 1.1

**Comment by sxyu** [comment]
Hi,
Sorry for slow response. I've been very busy recently.
The original code only supported SMPL-X v1.0 (20 shape blendshapes). 
I've updated it to make SMPL-X v1.1 default. Please check if it works.
